### ISSUE TITLE
No such widget `autosuggest-orig-history-substring-search-up'

### ISSUE THREAD

**Issue by bricewge** [tarruda/zsh-autosuggestions#103]
When I use `zsh-history-substring-search` with the v0.1.x branch and try to browse the history on a empty input I get `No such widget 'autosuggest-orig-history-substring-search-up'` and can't go through the history. However it work as expected if the input as at least 1 character.

My setup is made of: 
- `zsh` 5.0.8,
- `termite` 10,
- `antigen`,
- `oh-my-zsh`.

**Comment by ericfreese** [comment]
Have you read [this note in the readme](https://github.com/tarruda/zsh-autosuggestions/tree/v0.1.x#zsh-history-substring-search) about history-substring-search?

**Comment by bricewge** [comment]
Yes I used the snippet present in the README and placed it after the initialization of `zsh-autosuggestions`.
If you need to see my configuration it is [here](https://github.com/bricewge/dotfiles/blob/master/zsh/zshrc) (note that I obviously tested it uncommented).

**Comment by ericfreese** [comment]
Try setting the env variables before calling autosuggest_start:

```
# *** Autosuggestion
# Didn't work for the moment, have to keep on eye on it
# https://github.com/tarruda/zsh-autosuggestions/
antigen bundle tarruda/zsh-autosuggestions --branch=v0.1.x

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

# Add history-substring-search-* widgets to list of widgets that clear the autosuggestion
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)
# Remove *-line-or-history widgets from list of widgets that clear the autosuggestion to avoid conflict with history-substring-search-* widgets
SH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")

autosuggest_start
```

**Comment by bricewge** [comment]
I already tried, it has the same result.

**Comment by ericfreese** [comment]
Dang. Silly question: Have you been creating a new shell session each time you test it?

**Comment by bricewge** [comment]
Yes, of course, I spawn a new terminal each time.

**Comment by thenitai** [comment]
Hate to be the guy... but same here. Added the suggestion but still having the same issue.

**Comment by frebib** [comment]
I noticed this a few days ago on my laptop and couldn't be bothered to fix it so switched to fish for the meanwhile. Just updated this today on my desktop and am experiencing the same issue. 

Here is the snippet of my .zshrc that when commented fixes the issue and disables the plugin.

```
source /usr/share/zsh/plugins/zsh-autosuggestions/autosuggestions.zsh
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init
```

**Comment by frebib** [comment]
Havit

**Comment by frebib** [comment]
Removing the `history-substring-search` oh-my-zsh plugin seems to fix the issue. Maybe that is to blame?

**Comment by thenitai** [comment]
True. However, this disables all kinds of other completion commands which are quite helpful. I think I wait until this is fixed.

**Comment by bricewge** [comment]
@frebib Actually `history-substring-search` from oh-my-zsh is `zsh-history-substring-search` which we know to cause this issue form the start.

**Comment by aly006** [comment]
+1, I am also having this issue

**Comment by ericfreese** [comment]
Can someone post a minimal zshrc configuration for reproducing this error?

**Comment by bricewge** [comment]
After trying to write a minimal configuration to reproduce this issue and don't succeed at it. I have managed to fix the issue, on my side, after reading the `README.md`... I only had to initialize `zsh-autosuggestions` **after** `zsh-syntax-highlighting` as written [here](https://github.com/tarruda/zsh-autosuggestions/tree/v0.1.x#zsh-syntax-highlighting).
This is still strange to me as the message error refer to `zsh-history-substring-search` when it come from `zsh-syntax-highlighting`.

Can some one confirm this is working for them?

**Comment by frebib** [comment]
Can confirm I observe the same behaviour. (I think you mean _before_ not **after**)

This is the snippet of my config:
```
source /usr/share/zsh/plugins/zsh-autosuggestions/autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)

zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init
#plugins=(history-substring-search zsh-completions)

plugins=(... history-substring-search ...)
source $ZSH/oh-my-zsh.sh
```

It seems that the issue occurs even with this configuration when reloading the .zshrc config into an already loaded terminal but not in a new one.

Having the config like this is better than many error messages but it does have the bizarre side-effect of not updating highlighting as I type, but still updating with arrow keys, tab etc. I'm sure that's a different issue though

**Comment by ericfreese** [comment]
Small issue, but this line

`source /usr/share/zsh/plugins/zsh-autosuggestions/autosuggestions.zsh`

should now be

`source /usr/share/zsh/plugins/zsh-autosuggestions/dist/autosuggestions.zsh`

**Comment by ericfreese** [comment]
Also, using `zle-line-init` and the `autosuggest-start` widget is now deprecated. Just call `autosuggest_start` after sourcing the plugin. See the readme for more info.

**Comment by bricewge** [comment]
@frebib Nice to see that it's fixed. I meant to say:
> Call `autosuggest_start` **after** sourcing `zsh-syntax-highlighting`.

As mentioned in `README.md`.

**Comment by thenitai** [comment]
While the initial error is now resolved the plugin now crashes my terminal window as soon as I enter a "space" after any command, i.e. "ping(space)".

I'm using iTerm2 and load all plugins with the zgen framework. Here is my setup:

In a .zgen file
```
source ~/.zsh/zsh-autosuggestions/dist/autosuggestions.zsh
zgen load zsh-users/zsh-syntax-highlighting
```
In .zshrc
```
ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")

ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)

autosuggest_start
```

**Comment by ericfreese** [comment]
Can you create a separate issue for this? I would bet it's unrelated to the
problem originally reported here.

On Sunday, February 7, 2016, Nitai <notifications@github.com> wrote:

> While the initial error is now resolved the plugin now crashes my terminal
> window as soon as I enter a "space" after any command, i.e. "ping(space)".
>
> I'm using iTerm2 and load all plugins with the zgen framework. Here is my
> setup:
>
> In a .zgen file
>
> source ~/.zsh/zsh-autosuggestions/dist/autosuggestions.zsh
> zgen load zsh-users/zsh-syntax-highlighting
>
> In .zshrc
>
> ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")
>
> ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)
>
> autosuggest_start
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarruda/zsh-autosuggestions/issues/103#issuecomment-181058588>
> .
>


-- 
Sent from my iPhone

**Comment by thenitai** [comment]
Done, created as #107
