### ISSUE TITLE
Conflicts with FZF (Tab does not show completion menu) and performance issues

### ISSUE THREAD

**Issue by balta2ar** [tarruda/zsh-autosuggestions#108]
Hello.

* After I have updated zsh-autosuggestions to the latest version, Tab key is not showing me completion menu anymore. E.g. when I'm in the root (`/`), I do: `% cd <Tab>` and nothing happens. Here is (almost) minimal zshrc:
``` zsh
eval `dircolors -b`
bindkey -e
autoload -U compinit promptinit colors zstyle+ zmv 
zmodload -i zsh/complist
compinit
promptinit
colors

source ~/rc.arch/bz/thirdparty/zsh-autosuggestions/dist/autosuggestions.zsh
autosuggest_start

# I tried uncommenting these lines -- same result
# ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")
# ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

fzf commit: 40d934e378ec2072c9d807f7ca1fca73bda1d13d
zsh-autosuggestions commit: f154d25fb3b734235bff7d508d885e7db851c4ca

* When I change directory in mc (midnight commander), I notice unusually high and irritating delay of about 400..500ms.

zsh version:
```
boltx64% zsh --version
zsh 5.2 (x86_64-unknown-linux-gnu)
```

OS: ArchLinux 4.3.3-2-ARCH x86_64

I tried putting `autosuggest_start` after fzf initialization and in plain terminal (terminator in my case) the effect is the same. In tmux, when I press Tab in such configuration, the session is simply closed as if I pressed C-d with no current input.

I've been using older version of fzf (several months old) and updated to the latest in hope that the problem will be fixed. It wasn't. I'm not sure which piece of software is playing wrong, but as there were recent substantial changes here, I'm reporting here. @ericfreese Could you look into this, please?

**Comment by adambiggs** [comment]
+1 I'm also having this problem.

**Comment by DannyNemer** [comment]
I also have this issue.

**Comment by ericfreese** [comment]
I believe v0.2.6 should fix this issue. Please give that a shot.

**Comment by balta2ar** [comment]
@ericfreese Thank you for your work, it indeed fixes the first of my issues! However, the second remains. I still have significant delay when changing directory in mc. Could there anything be done about that?

**Comment by ericfreese** [comment]
Good! Can you add a separate issue for that (with as much info as possible to reproduce that specific problem)?

**Comment by adambiggs** [comment]
Fixed for me, thanks! :beers:

**Comment by DannyNemer** [comment]
Fixed! Thank you for your excellent work!
