### ISSUE TITLE
Terminal freezes when pasting text

### ISSUE THREAD

**Issue by KarthikNayak** [tarruda/zsh-autosuggestions#112]
I'm using zsh-autosuggestions with oh-my-zsh. Recently I had the time to update zsh-autosuggestions and this broke my setup. Now if I paste text onto the terminal, it freezes. 

```
# Load zsh-autosuggestions.
source ~/.oh-my-zsh/zsh-autosuggestions/dist/autosuggestions.zsh
autosuggest_start
```

I had no problems with zsh-autosuggestions and paste before this. 
Commenting out the config, ensures that the problem is due to zsh-autosuggestions. 

OS: Arch Linux
Zsh --version: zsh 5.2 (x86_64-unknown-linux-gnu)

**Comment by ericfreese** [comment]
This is related to `bracketed-paste-magic`. See #102.

**Comment by KarthikNayak** [comment]
@ericfreese Didn't see that, thanks.
