### ISSUE TITLE
Autosuggestion isn't cleared after pressing Ctrl+U

### ISSUE THREAD

**Issue by florian** [tarruda/zsh-autosuggestions#114]
Ctrl+U deletes everything from the cursor to the beginning of the line. However the autosuggestion won't get cleared.
Is this a bug or do I need to change some setting?

**Comment by ericfreese** [comment]
This should be fixed with v0.2.5. It wasn't binding to the `kill-whole-line` widget.

**Comment by florian** [comment]
Yep, it's working now!
Thanks for the quick fix :)
