### ISSUE TITLE
0.2.5 causes history-substring-search-up to crash the zsh session, even when setting the options recommended by README

### ISSUE THREAD

**Issue by ronjouch** [tarruda/zsh-autosuggestions#115]
Reproduction scenario:

* Oh-my-zsh with only `plugins=(zsh-autosuggestions)` and
```
ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)
```
* In an empty line, press `Up`

**Expected**: show my last-used command (vanilla bash/zsh behavior). `history-substring-search` should be triggered only on non-empty lines.

**Actual**: `No such widget 'history-substring-search-up'`, and the last-used command is not displayed.

I *think* this started to happened at 0.2.3 or 0.2.5.

**Comment by ericfreese** [comment]
Are you sourcing the `zsh-history-substring-search.zsh` file somewhere to define the `history-substring-search-up` and `history-substring-search-down` widgets?

**Comment by ronjouch** [comment]
@ericfreese hmkay, so this is a funny one. Please ignore the title: as you're saying (and as I'm describing when I say I'm only loading `plugins=(zsh-autosuggestions)`), the reproduction scenario I'm describing as an attempt to narrow down on the issue is completely borked.

Here's my initial, real problem with 0.2.something:

* On an empty line,
* Press up

→ Zsh exits silently.

Am trying to precise the issue.

**Comment by ronjouch** [comment]
@ericfreese so I think I'm hitting the infinite recursion problem described in [README](https://github.com/tarruda/zsh-autosuggestions#zsh-history-substring-search) ending up a crash. But I *am* setting the options you recommend (just like I have been for months!). Below is a minimal reproduction `.zshrc`. What am I doing wrong?

```bash
ZSH=$HOME/.oh-my-zsh
plugins=(zsh-autosuggestions history-substring-search)
source $ZSH/oh-my-zsh.sh
ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)
```

**Comment by ronjouch** [comment]
@ericfreese trying successive versions, I confirm that v0.2.5 is the first version with the problem.

**Comment by ipod825** [comment]
I also have problems with version 0.2.5

Here's minimum zshrc to reproduce the error
```bash
##ANTIGEN                                                                                                                             
GEN_HOME=$HOME/.antigen                                            
if ! [[ -d $GEN_HOME ]]                                            
then                                                               
git clone https://github.com/zsh-users/antigen.git $GEN_HOME       
fi                                                                 
source "$GEN_HOME/antigen.zsh"                                     
antigen bundle tarruda/zsh-autosuggestions                         
antigen bundle zsh-users/zsh-history-substring-search              
                                                                                               
HISTFILE=~/.zsh_history                                            
zmodload zsh/terminfo                                              
bindkey "$terminfo[kcuu1]" history-substring-search-up             
bindkey "$terminfo[kcud1]" history-substring-search-down           
bindkey '^[[A' history-substring-search-up                         
bindkey '^[[B' history-substring-search-down                       
                                                                   
ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")                                      
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(_history-substring-search-begin history-substring-search-up history-substring-search-down ) 
```

Pressing up key on empty lines result in Error ```_history-substring-search-begin:30: job table full or recursion limit exceeded ```

**Comment by ericfreese** [comment]
I've just pushed v0.2.6, which I believe fixes all infinite recursion issues. Please give that a shot.

**Comment by ipod825** [comment]
Yeah, the problem is solved. Thanks a lot.
