### ISSUE TITLE
Text color on right of cursor

### ISSUE THREAD

**Issue by purplefish32** [tarruda/zsh-autosuggestions#12]
On my install (zsh, terminator, crunchbang/debian) the text on the right is not grey, it is the same color as the left.
I dont know if this is a bug or if this is just my setup but its really annoying.

**Comment by fboulay** [comment]
Other way to solve this problem is to have the 256 zsh color plugin : https://github.com/chrissicool/zsh-256color

**Comment by uetchy** [comment]
:+1: solved this problem with changing xterm to xterm-256color.

**Comment by pedro-nonfree** [comment]
I had a problem with Function keys and Shift with byobu.co, the solution was:
export TERM=screen-256color

src https://bbs.archlinux.org/viewtopic.php?pid=1456235#p1456235

**Comment by Marvel77** [comment]
hey guys, I have mac os el capitan standart terminal and same issue, solved by setting terminal to xterm-256color and adding `export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"` to the end of the `.zshrc`. 
Just sharing in case it will help to somebody. Cheers!

**Comment by jinwyp** [comment]
Thanks @Marvel77

**Comment by amrutjadhav** [comment]
@fboulay Thanks for solution. Worked for me.

**Comment by FWoelffel** [comment]
@Marvel77's solution was the way to go for me (using Terminator). Thanks!

**Comment by mludi** [comment]
Thanks @Marvel77 worked for me too :)

**Comment by bcromijn** [comment]
Thanks @Marvel77, works on iTerm2 with .zsh

**Comment by ikirmitz** [comment]
@fboulay suggestion to install 256 zsh color plugin did the trick for me on Ubuntu and Guake

**Comment by magickaichen** [comment]
@Marvel77 thanks for the posting, works for me!

**Comment by cpxPratik** [comment]
Thanks @Marvel77 , just adding `export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=cyan"` at the end of `.zshrc` config file worked (Uubntu 16.04, zsh with oh-my-zsh). BTW, do `source ~/.zshrc` to reload config on current terminal or open new terminal to see changes.

**Comment by thamenato** [comment]
Tks @Marvel77 , worked here on urxvt

**Comment by braanan** [comment]
Here's a useful link to a full [xterm-256-color chart](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg) (wikipedia). You can specify the color code you

**Comment by sisrfeng** [comment]
I think this is correct: 
1. setting terminal to xterm-256color and
2. adding export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3" to the end of the .zshrc.

To add `export TERM="xterm-256color" `  in .zshrc ?

I think we should not.

https://unix.stackexchange.com/questions/139082/zsh-set-term-screen-256color-in-tmux-but-xterm-256color-without-tmux

> zsh might care what your TERM is set to   if it wants to do special things, but it should not be responsible for setting it

**Comment by McArni91** [comment]
If you use iTerm, the autosuggestion color is the "Bright Black" on the Profiles > Color edit.
