### ISSUE TITLE
fails to suggest more that 15 commands into history

### ISSUE THREAD

**Issue by a-m-s** [tarruda/zsh-autosuggestions#120]
If the command does not appear in `fc -l` then it will not be suggested.

A larger number needs to be specified: `fc -l -1000000` perhaps?

**Comment by ericfreese** [comment]
Ah, I wasn't sure about using `fc` but it seemed to work locally so I thought I'd go with it. Didn't quite understand this part in the docs: 

> If first is not specified, it will be set to -1 (the most recent event), or to -16 if the -l flag is given.

but it looks like that's the problem.

Probably will go back to the previous way of finding a suggestion, but add `unsetopt localoptions sh_word_split` to the top of the function.

**Comment by a-m-s** [comment]
Just specifying a million commands, like in my example, is probably sufficient.

**Comment by ericfreese** [comment]
Ok instead of making a whole new release, how about you check out the `v0.2.x` branch. It should fix the problem by forcing field splitting on null character \0.

**Comment by ronjouch** [comment]
I confirm this v0.2.9 bug, and I confirm that 6d25df68641369876614b216826e138b3f67aa5b in branch v0.2.x fixes it. Zsh 5.2 + oh-my-zsh.

**Comment by a-m-s** [comment]
The fix seems to work.

**Comment by ericfreese** [comment]
Ok, pushed up a new version v0.2.10 with that fix.
