### ISSUE TITLE
Encountered in the process of installing a bug

### ISSUE THREAD

**Issue by cynhard** [tarruda/zsh-autosuggestions#121]
-bash: zle: command not found
-bash: /Users/cynhard/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 117: syntax error near unexpected token `('
-bash: /Users/cynhard/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 117: `		user:_zsh_autosuggest_(bound|orig)_*);;'

I have no idea about this.

**Comment by ericfreese** [comment]
> I have no idea about this.

Are you running zsh? It looks like you're trying to source this plugin from a bash session, but this plugin only works for zsh. Install zsh, make sure you're running zsh, and then try again.

**Comment by cynhard** [comment]
Got it! Thanks very much!

**Comment by cynhard** [comment]
@ericfreese Got it! Thanks very much!
