### ISSUE TITLE
Could we ignore widget `forward-char` to accept a suggestion?

### ISSUE THREAD

**Issue by hitripod** [tarruda/zsh-autosuggestions#123]
In some cases, I typed `forward-char` to step ahead char-by-char to accept partial suggestion.

For example, I first type `cd` and then the suggesstion shown up is `cd ~/.zsh/zsh-autosuggestions`. In this case, if the directory I really want to change to is `~/.zsh`, only thing I can do is  type every chars instead of using `forward-char`.

Could we ignore widget `forward-char` to accept a suggestion?

```javascript
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
-   forward-char
    end-of-line
-   vi-forward-char
    vi-end-of-line
)
```

**Comment by ericfreese** [comment]
See my comment [here](https://github.com/tarruda/zsh-autosuggestions/issues/93#issuecomment-175939916) to configure the forward-char widget to partially accept the suggestion. I'd like to keep forward-char accepting the suggestion by default as it does in the fish shell.

**Comment by hitripod** [comment]
Understood, thanks.
