### ISSUE TITLE
_zsh_autosuggest_suggestion:local:1: not valid in this context:

### ISSUE THREAD

**Issue by nikoren** [tarruda/zsh-autosuggestions#127]
Hi,

Anytime i type "--" 
 I  get following message:  ```_zsh_autosuggest_suggestion:local:1: not valid in this context: 

```
xxx-mac% ansible -_zsh_autosuggest_suggestion:local:1: not valid in this context: --
-_zsh_autosuggest_suggestion:local:1: not valid in this context: --
_zsh_autosuggest_suggestion:local:1: not valid in this context: --
_zsh_autosuggest_suggestion:local:1: not valid in this context: ---
-_zsh_autosuggest_suggestion:local:1: not valid in this context: ---
_zsh_autosuggest_suggestion:local:1: not valid in this context: --
_zsh_autosuggest_suggestion:local:1: not valid in this context: --v
v_zsh_autosuggest_suggestion:local:1: not valid in this context: --ve
e_zsh_autosuggest_suggestion:local:1: not valid in this context: --ve
_zsh_autosuggest_suggestion:local:1: not valid in this context: --v
```

**Comment by arianf** [comment]
I am getting a similar error.... after upgrading and moving my autosuggestions from `~/.zsh` to a oh-my-zsh plugin `~/.oh-my-zsh`

```
git co -_zsh_autosuggest_suggestion:local:1: not valid in this context: -b/plugins/zsh-autosuggestions
b_zsh_autosuggest_suggestion:local:1: not valid in this context: -b                           
 _zsh_autosuggest_suggestion:local:1: not valid in this context: -b
f_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
s_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
f_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
a_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
s_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
d_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
f_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
a_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
s_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
d_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
f_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
a_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
s_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
d_zsh_autosuggest_suggestion:local:1: not valid in this context: -b
f
```

**Comment by arianf** [comment]
It won't go away... makes terminal completely unusable...

```
st _zsh_autosuggest_suggestion:local:1: not valid in this context: ~
~_zsh_autosuggest_suggestion:local:1: not valid in this context: ~a
a_zsh_autosuggest_suggestion:local:1: not valid in this context: ~as
s_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asd
d_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdf
f_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdfa
a_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdfad
d_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdfadf
f_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdfadfa
a_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdfadfas
s_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdfadfasd
d_zsh_autosuggest_suggestion:local:1: not valid in this context: ~asdfadfasdf
f
```

**Comment by ericfreese** [comment]
Thanks for reporting this. For now, you can see if using [`v0.2.13`](https://github.com/tarruda/zsh-autosuggestions/tree/v0.2.13) will solve this problem.

In the meantime, it would be helpful for me to be able to recreate this problem. Would either of you be willing to determine a minimal .zshrc configuration that creates this problem?

**Comment by ronjouch** [comment]
Bug confirmed here. Also,

* It's not just `--`, it's any non-word character (`~`, `/`, `1`) as argument. For example, if I type `cd ~`, I see: `cd _zsh_autosuggest_suggestion:local:1: not valid in this context: ~`
    * With digits though, the error message varies. For example, `cd 1` displays `cd _zsh_autosuggest_suggestion:local:1: not an identifier: 1`
* Reverting to `v0.2.13` solves the problem.

Zsh 5.2 on Linux with oh-my-zsh with plugins `(python pip virtualenvwrapper npm httpie git sudo docker colored-man-pages history-substring-search zsh-navigation-tools zsh-autosuggestions zsh-syntax-highlighting)`, which I'll reduce to a minimal `.zshrc` this evening at home if no one provided one before.

**Comment by arianf** [comment]
Yup version 0.2.13 solves the issue for me...

Workaround steps:

```bash
cd ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git co "v0.2.13"
# restart terminal
```

**Comment by ericfreese** [comment]
I'm trying to reproduce, but not having any success.

My ~/.zshrc:

```shell
% cat ~/.zshrc
export ZSH=/Users/ericfreese/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(python pip virtualenvwrapper npm httpie git sudo docker colored-man-pages history-substring-search zsh-navigation-tools zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
```

Zsh version:

```shell
% zsh --version
zsh 5.2 (x86_64-apple-darwin14.5.0)
```

Oh My Zsh version:

```shell
% git -C $ZSH rev-parse --short HEAD
bd6dbd1
```

zsh-autosuggestions version:

```shell
% git -C $ZSH_CUSTOM/plugins/zsh-autosuggestions/ rev-parse --short HEAD
9d100f4
```

And the plugin seems to work as expected... I think I'll need more info here before I can do much more than make shots in the dark. Looking forward to your minimal config @ronjouch!

**Comment by arianf** [comment]
I was able to repo with very minimal `~/.zshrc`

```bash
cat ~/.zshrc
export ZSH=$HOME/.oh-my-zsh
plugins=(zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
```

Zsh version:

```bash
zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

Oh My Zsh version:

```bash
git -C $ZSH rev-parse --short HEAD
534bf2c
```

zsh-autosuggestions version:

```
git -C $ZSH_CUSTOM/plugins/zsh-autosuggestions/ rev-parse --short HEAD
9d100f4
```

The problem was introduce here: 

`git diff 2a57917..ddb7284`

The issue doesn't exist on `2a5791`

**Comment by arianf** [comment]
This is how the error is being created:

```bash
test() {
    echo " ~"
}

local prefix=$(test)
```

**Comment by arianf** [comment]
Something like this might work better

```bash
local prefix="$(_zsh_autosuggest_escape_command_prefix "$1")"
```

**Comment by arianf** [comment]
Another thing to note, the new match is missing `#<>~^`

```bash
"${1//(#m)[\\()\[\]|*?]/\\$MATCH}" #new 
"${1//(#m)[\][()|\\*?#<>~^]/\\$MATCH}" #old
```

**Comment by ronjouch** [comment]
> And the plugin seems to work as expected... I think I'll need more info here before I can do much more than make shots in the dark. Looking forward to your minimal config @ronjouch!

@ericfreese cannot reproduce at home either, even though it's the same {zsh, oh-my-zsh,tmux} versions and the same `.zshrc` :-/ . Will try to narrow down tomorrow at work if the information provided above by @arianf didn't help.

**Comment by ericfreese** [comment]
> This is how the error is being created:

Interestingly, this works just fine in my terminal:

```shell
% /bin/zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
% /bin/zsh -f
%% test() { echo " ~" }
%% abc=$(test)
%% echo $abc
 ~
```

@arianf What is the output of `setopt` for you? Mine (in the example above) is:

```shell
% setopt
interactive
monitor
norcs
shinstdin
zle
```

> Wrapping the right side with quotes should fix this.

This was going to be my shot-in-the-dark fix. I'll go ahead and make this change, but I'm still curious why it works for me but not for others.

> Another thing to note, the new match is missing #<>~^

I removed these because they didn't actually appear necessary when I was testing. I had originally just copied this line from [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search/blob/e2ab5b8214c50c2cb39d370fe4863576fd3eeffe/zsh-history-substring-search.zsh#L198), but thought I'd trim it down to only what was needed. We can add those characters back in as we find the need for them.

**Comment by ericfreese** [comment]
Ok, this appears to be a zsh version thing:

```shell
% /bin/zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
% /bin/zsh -f
%% source ~/Code/zsh-autosuggestions/zsh-autosuggestions.zsh
%% echo _zsh_autosuggest_suggestion:local:1: not valid in this context: ~
~
```

On the last line, I typed "echo ~" and got the error when I hit the "~" key.

And @arianf's suggestion, fixes it. Gonna go ahead and add that and push a new release.

Thanks all! :+1:
