### ISSUE TITLE
Suggestion not completely cleared upon interactive menu select

### ISSUE THREAD

**Issue by aw1621107** [tarruda/zsh-autosuggestions#128]
When entering menu-select's interactive mode, the autosuggested color goes away, but the characters do not.

I enabled interactive mode by adding `zstyle ":completion:*" menu select interactive` to my `.zshrc`

Ex:
<img width="922" alt="suggestion" src="https://cloud.githubusercontent.com/assets/566572/13307227/ca803e18-db37-11e5-94cf-ab6a941b8621.png">
After hitting tab once:
<img width="922" alt="possible completions" src="https://cloud.githubusercontent.com/assets/566572/13307228/cbda6608-db37-11e5-9961-ddee14e04825.png">
Hitting tab again for menu completion:
<img width="922" alt="interactive" src="https://cloud.githubusercontent.com/assets/566572/13307229/cd74f03c-db37-11e5-81bc-d276f2f3ec27.png">
I would have expected the "shrc" to have been deleted and replaced with "compdump". The color vanishes, but not the characters.
Using the arrow keys to pick an option:
<img width="922" alt="arrow" src="https://cloud.githubusercontent.com/assets/566572/13307360/a33b3776-db38-11e5-9f87-e4aee8b6252c.png">
Extra characters are still here
After hitting enter:
<img width="922" alt="selected" src="https://cloud.githubusercontent.com/assets/566572/13307366/ad8bfd3c-db38-11e5-9006-8ca324514ffd.png">
Characters disappeared on their own.

**Comment by ericfreese** [comment]
I believe this is a duplicate of #118. Check out that issue for a couple potential workarounds.

**Comment by aw1621107** [comment]
Indeed it is. My apologies for not searching more thoroughly.

**Comment by aw1621107** [comment]
Indeed it is. My apologies for not searching more thoroughly.
