### ISSUE TITLE
vi-end-of-line does not highlight text properly

### ISSUE THREAD

**Issue by alexbw** [tarruda/zsh-autosuggestions#13]
On the current master,  `bindkey '^f' vi-end-of-line` properly autocompletes, but does not change the autocompletion color.

**Comment by jirutka** [comment]
> how about for completion and execution all in one shot?

@257 I’ve implemented it in #61, `autosuggest-execute-suggestion`.

**Comment by jirutka** [comment]
@faceleg This shouldn’t be closed, the problem described in the title is still here. I’ll take a look at it later.

**Comment by 257** [comment]
(going out on a tangent here)
@jirutka  this might interest you:
https://github.com/fish-shell/fish-shell/issues/1465

**Comment by 257** [comment]
@jirutka and so might these:
https://github.com/hchbaw/auto-fu.zsh/issues/36
https://github.com/fish-shell/fish-shell/issues/1419

i can open a new issue for this (i.e. backspace deletes suggestion first and only then it starts deleting typed chars), just let me know.

i'm using auto-fu right now but i'm willing to switch to zsh-autosuggestions and help out in anyway i can if i see progress on this.

**Comment by faceleg** [comment]
My bad!

**Comment by jirutka** [comment]
@faceleg Please add “bug” tag to this issue.

**Comment by ericfreese** [comment]
There's a rewrite underway in PR #91. It's available on branch `v0.1.x`. Please try using that branch, and let me know if it solves your problem.
