### ISSUE TITLE
error with up/down-line-or-history widget

### ISSUE THREAD

**Issue by vapniks** [tarruda/zsh-autosuggestions#22]
When I press my up/down arrow key to invoke the up/down-line-or-history widgets, I get the following error: autosuggest-suspend:1: job table full or recursion limit exceeded

**Comment by george-b** [comment]
I was having a similar issue when attempting to use things like ctrl-e and ctrl-w I moved the sourcing of `autosuggestions.zsh` to the end of my zshrc and this seems to have resolved the issue for now. I should also note I'm using zsh-syntax-highlighting also.

**Comment by faceleg** [comment]
Moving it to the bottom had no effect for me.

**Comment by vapniks** [comment]
I've put a bounty on this, feel free to add to it, or try and claim it: https://www.bountysource.com/issues/1513861-error-with-up-down-line-or-history-widget

**Comment by ikhthiandor** [comment]
Relevant thread.
http://www.zsh.org/mla/workers/2002/msg01076.html

**Comment by faceleg** [comment]
Anyone had luck resolving this?

**Comment by ronjouch** [comment]
I bump into this too when I fiddle with configuration and re-source my `.zshrc`. Usually, killing my terminal (and having it being relaunched by tmux) solves the issue, and in normal terminal usage I never encounter the problem.

**Comment by faceleg** [comment]
I can verify this! thanks @ronjouch

**Comment by liviu-** [comment]
Is there really no more convenient solution than restarting the terminal?

**Comment by calincru** [comment]
What's the status of this?  I recently started getting this error while using tmux.  As I see @ronjouch mentioned tmux too, does it have anything to do with it?  Thanks!

**Comment by ericfreese** [comment]
Are you using the most recent version of the plugin?
