### ISSUE TITLE
Unexpected Backspace (backward-delete-char) Behaviour

### ISSUE THREAD

**Issue by CallumHoward** [tarruda/zsh-autosuggestions#33]
![screen shot 2014-09-16 at 9 32 35 pm](https://cloud.githubusercontent.com/assets/7144420/4286491/9e71fba4-3d95-11e4-9cd9-1aee52acc0f1.png)
When typing, autosuggest behaves as expected. However when the backspace button is pressed, the suggestion is not cleared from the line as in Fish
![screen shot 2014-09-16 at 9 32 54 pm](https://cloud.githubusercontent.com/assets/7144420/4286507/cd4b0a92-3d95-11e4-87c0-96919108e02c.png)
The suggestion is cleared upon entering vi-command-mode.
zsh version: zsh 5.0.2 (x86_64-apple-darwin13.0)
other plug-ins: history-substring-search zsh-syntax-highlighting
using oh-my-zsh

**Comment by jirutka** [comment]
Please try the recent version of zsh-autosuggestions, it should be already fixed.
