### ISSUE TITLE
Integration with zprezto

### ISSUE THREAD

**Issue by samupl** [tarruda/zsh-autosuggestions#37]
It would be nice to be able to use zsh-autosuggestions with prezto (https://github.com/sorin-ionescu/prezto). There are a few issues with it, especially with the 'history-substring-search' module. 

A simple, bare install of prezto and zsh-autosuggestions doesn't seem to be working properly.

**Comment by darfink** [comment]
Would love this enhancement as well.

**Comment by faceleg** [comment]
Now accepting pull requests!

**Comment by N4M3Z** [comment]
This plugin is of course compatible with `prezto`, it is simply the matter of a correct load order:
```
zstyle ':prezto:load' pmodule \
    "history" \
    "completion" \
    "history-substring-search" \
    "syntax-highlighting" \
    "autosuggestions" \
```

**Comment by samupl** [comment]
This however seems to break the sorin theme of zpreztorc. The command prompt seems to dissapear at the first shell load (it appears again after the first command has failed/succeeded).

**Comment by faceleg** [comment]
Open for a PR that includes updates to the readme regarding how to make this work well with prezto

**Comment by N4M3Z** [comment]
@samupl I am using powerline, which seems to be working fine.

**Comment by breerly** [comment]
@N4M3Z how did you actually install autosuggestions? I'm trying to get it working w prezto on the minimal theme and having no luck :(

**Comment by N4M3Z** [comment]
Follow my commits here: https://github.com/N4M3Z/zsh-core/commits/module/autosuggestions, or just use my fork of Prezto entirely. The module is initialized like this: https://github.com/N4M3Z/zsh-core/commit/29756c7831838992961b5b093f2e6315bc02acc8

**Comment by breerly** [comment]
cc @sorin-ionescu ^^

**Comment by breerly** [comment]
@N4M3Z any chance you could submit a PR upstream?

**Comment by sorin-ionescu** [comment]
@breerly There should be a [modules/autosuggestions](https://github.com/sorin-ionescu/prezto/tree/module/autosuggestions) branch in Prezto. Feel free to modify that.

**Comment by breerly** [comment]
@sorin-ionescu any reason we cant get autosuggestions in master?

**Comment by sorin-ionescu** [comment]
That's the work branch, which was created when I first tested zsh-autosuggestions.

**Comment by N4M3Z** [comment]
@breerly My fork of Prezto is slightly modified and relies mainly on this commit: https://github.com/N4M3Z/zsh-core/commit/21ecc2ce9889cf374d364dc555c4ad24364b1625, it autoloads modules using `functions.zsh`, `aliases.zsh` and `bindings.zsh` files instead of just `init.zsh`. As this is not going to make it to Prezto master, you would have to adapt it to suit your needs.

**Comment by sorin-ionescu** [comment]
@N4M3Z I don't recall having a discussion with you about splitting files.

**Comment by N4M3Z** [comment]
@sorin-ionescu It was some time ago: https://github.com/sorin-ionescu/prezto/issues/860, I did not actually submit a pull request, but I can sure do that if you are interested.

**Comment by breerly** [comment]
Would love to get this in!!!
