### ISSUE TITLE
Install fails on Mac (no option -e for readlink)

### ISSUE THREAD

**Issue by Gaffney** [tarruda/zsh-autosuggestions#38]
There is no `-e` option on the `readlink` installed on Mac OSX, so the install fails completely (see L11 on `install` [here](https://github.com/tarruda/zsh-autosuggestions/blob/master/install#L11))

    bash-3.2$ sh /Users/me/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-tarruda-SLASH-zsh-autosuggestions.git/install
    readlink: illegal option -- e
    usage: readlink [-n] [file ...]
    usage: dirname path
    
    Setup completed successfully!

Refer to this commit: 32fb7930d825a4c04aedcd2972c2447bfc9adc51

**Comment by Gaffney** [comment]
@faceleg I don't think this fixes it.  Compare the Linux `readlink -f` to the Mac version:

**Linux**

    -f, --canonicalize
        canonicalize by following every symlink in every component
        of the given name recursively; all but the last component must exist

**Mac**

    -f format
        Display information using the specified format.  
        See the FORMATS section for a description of valid formats.

See also:

- [StackOverflow: How can I get the behavior of GNU's readlink -f on a Mac?](http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac)

**Comment by faceleg** [comment]
Thanks, reopening.

Seeing as you have quick access to a mac (I assume), would you mind fixing this?

**Comment by Gaffney** [comment]
I thought about it for a bit and I could not think of a clean fix, as installing `coreutils` is not a viable option.  (That is what I did to fix it locally).

Can possibly think about it / fix it later this week or next when I am not so busy.

**Comment by faceleg** [comment]
We could use something like: 


```sh
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
```

From http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

**Comment by bfred-it** [comment]
@faceleg's code seems to work for me (OSX 10.10)

**Comment by Gaffney** [comment]
@bfred-it Are you referring to what was committed or the script [above](https://github.com/tarruda/zsh-autosuggestions/issues/38#issuecomment-69258372)?

**Comment by bfred-it** [comment]
Script above my comment

**Comment by Gaffney** [comment]
Cool, can you make a PR with your install file?
