### ISSUE TITLE
pressing up arrow only does the expected thing once

### ISSUE THREAD

**Issue by sandover** [tarruda/zsh-autosuggestions#43]
Input:

```
» echo "hi"                                              
hi
» echo "bye"                                              
bye
```

- type in "echo"
- press up arrow once: expected result is ```echo "hi"```.  Pass
- press up arrow again.  expected result is ```echo "bye"```.  Actual result: something random.  :(  
- Press up arrow a few more times: a random walk through history.  

In fish, the result would be an orderly series of results which start with "echo"

**Comment by faceleg** [comment]
This is a known bug, currently the repo is strongly in need of someone to jump in and do some serious coding - want the job?

**Comment by sandover** [comment]
Point taken!  I don't know if I'm the one, though.  :-/

**Comment by faceleg** [comment]
The wait continues.

**Comment by jirutka** [comment]
Just a hint: I’m using autosuggestions together with [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search) plugin and it works correctly here.
