### ISSUE TITLE
Clarification of install operations

### ISSUE THREAD

**Issue by tirkarthi** [tarruda/zsh-autosuggestions#44]
The installation instruction asks users to run `sh ~/.zsh-autosuggestions/install` for installation. But sh is symlinked to dash in ubuntu 12.04 and probably in many Debian distros. Since dash doesn't support `SOURCE="${BASH_SOURCE[0]}"` it throws up an error. It will be good if there is an explanation for this in the instructions for Debian based distros to run it with bash or to ask users to run it with `/bin/bash` directly.

**Comment by faceleg** [comment]
Please feel free to update the README - I will immediately merge such a PR

**Comment by tirkarthi** [comment]
Closing the issue with the merge of [pull request 45](https://github.com/tarruda/zsh-autosuggestions/pull/45)
