### ISSUE TITLE
install script emits bad characters on cygwin

### ISSUE THREAD

**Issue by apjanke** [tarruda/zsh-autosuggestions#46]
The `install` script has a cosmetic issue when running on Cygwin/Windows 7 for me. The `\n` characters are printed literally instead of turning in to newlines, even when explicitly run under `bash`.

![install on cygwin-win7 under mintty](https://cloud.githubusercontent.com/assets/2618447/6477483/41afeba6-c1f2-11e4-841d-106b8201020e.png)

This is on Windows 7, with Cygwin updated as of about 1/25/2015.

```
$ uname -a
CYGWIN_NT-6.1 gwydion 1.7.34(0.285/5/3) 2015-02-04 12:14 x86_64 Cygwin
```

I think this is because `echo` is non-portable when used with escape sequences or options. Different shells and even different `bash`es might behave differently on different systems. Described [here](http://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo). It'll probably affect Fedora 21 and FreeBSD as well, based on a similar issue I've seen with oh-my-zsh (robbyrussell/oh-my-zsh#3658).

Looks like it could be fixed by replacing `echo` with `printf` calls.

**Comment by jirutka** [comment]
I recommend to just not use this installation script and copy those few lines manually according to new instructions in the [readme](https://github.com/tarruda/zsh-autosuggestions#installation).
