### ISSUE TITLE
No such shell function `autosuggest-accept-suggested-small-word'

### ISSUE THREAD

**Issue by l4u** [tarruda/zsh-autosuggestions#48]
I am trying to bind a key to this function.

**Comment by jirutka** [comment]
This widget is defined [here](https://github.com/tarruda/zsh-autosuggestions/blob/bbd5300d605ea60fccb35c98315d936faa2fc319/autosuggestions.zsh#L260), but the function indeed doesn’t exist. Maybe it’s just some historical remnant?

What do you expect from this widget to do? Perhaps we can implement it, but I have no clue what it’s supposed to do.
