### ISSUE TITLE
"~/.zshrc file does not exist or is not readable"

### ISSUE THREAD

**Issue by teto** [tarruda/zsh-autosuggestions#50]
I get the error in the title. Indeed my file does not exist since I use .zshenv to set ZDOTDIR.
The script should check if $ZDOTDIR exists and use $ZDOTDIR/.zshrc when it does.

**Comment by faceleg** [comment]
Great find! We accept pull requests :)

**Comment by jirutka** [comment]
This is already fixed, #51.
