### ISSUE TITLE
Provide instructions for uninstallation

### ISSUE THREAD

**Issue by ikhthiandor** [tarruda/zsh-autosuggestions#54]

**Comment by baykovr** [comment]
Can't speak for the author but here's what I did:

Remove the repository folder:

     rm ~/.zsh-autosuggestions -rf

Remove the lines appended to the end of .zshrc by the install script (by hand):
   
    # Setup zsh-autosuggestions
    source /home/you/.zsh-autosuggestions/autosuggestions.zsh
    
    # Enable autosuggestions automatically
    zle-line-init() {
        zle autosuggest-start
    }

    zle -N zle-line-init

    # use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
    # zsh-autosuggestions is designed to be unobtrusive)
    bindkey '^T' autosuggest-toggle

**Comment by ikhthiandor** [comment]
Thanks @baykovr for responding. I also did the same, forgot to remove the directory though.

**Comment by faceleg** [comment]
Does someone want to add this to the readme ?

**Comment by jirutka** [comment]
I’ve described uninstallation in the readme [here](https://github.com/tarruda/zsh-autosuggestions#uninstallation).
