### ISSUE TITLE
Autosuggestions do not work with zsh-syntax-highlighting

### ISSUE THREAD

**Issue by ZyX-I** [tarruda/zsh-autosuggestions#6]
It is somewhat expected since both plugins are using the same zle widgets. I guess you need to cooperate and work out some standard that will allow using both plugins.

Fish has both completion and highlighting and it looks nice. I do not like much more limited capabilities of it though.

**Comment by balta2ar** [comment]
@tarruda I'm experiencing the same problem :( Have to live on detached HEAD because up-to-date versions of zsh-autosuggestions and zsh-syntax-highlighting don't play well together. Is there any chance you could look into this problem once again, please?

**Comment by tarruda** [comment]
> Is there any chance you could look into this problem once again, please?

Not in the foreseeable future, sorry.

**Comment by faceleg** [comment]
@balta2ar we need someone with time & zsh experience to refactor some of this :8ball:

**Comment by santiycr** [comment]
Just in case others are struggling with this one while using prezto. If when you submit commands with active auto-suggestions, they loose their highlighting and get confusing with the actual command that was run:
![2016-05-19_16-53-36](https://cloud.githubusercontent.com/assets/105375/15435674/8e27ec12-1e72-11e6-8ff8-77f1db5c2a0d.png)

(notice, I had typed and submitted `git a`, while the rest was grayed out before submitting)

The following `syntax-highlighting` cleared the issue for me:
https://github.com/sorin-ionescu/prezto/tree/master/modules/syntax-highlighting#highlighting

**Comment by iamsandesh** [comment]
I was struggling with this issue, then I loaded the 'autosuggestions' module after the 'syntax-highlighting' module then both the modules seems to be working fine.

I also enabled the coloring for 'autosuggestions' by uncommenting the below line
 zstyle ':prezto:module:autosuggestions:color' found 'blue'

**Comment by schlichtanders** [comment]
@iamsandesh that sounds really good! can you explain where to find this line?

**Comment by iamsandesh** [comment]
I am updating it in the "~/.zprezto/runcoms/.zpreztorc" file which is present in $HOME folder. 

The line is already present in the file but commented out, so the line needs to be uncommented and the color has to be specified in that line as it is not already specified.

**Comment by psprint** [comment]
I've debugged my `fast-syntax-highlighting` (`z-sy-h` fork) and it's like it is described in #260 – `builtin zle "$@"` returns `1` and `_zsh_highlight` isn't run. So I patched my `f-sy-h`:

```diff
 _zsh_highlight_call_widget()
 {
-  builtin zle "$@" && _zsh_highlight
+    # Changed for compatibility with zsh-autosuggestions
+    # Was: builtin zle "$@" && _zsh_highlight
+    builtin zle "$@"
+    _zsh_highlight
```
I think there is no situation when not-highlighting after user action is a good choice. You can test `zdharma/fast-syntax-highlighting`, one could then submit to `z-sy-h` if such change helps.
