### ISSUE TITLE
autosuggestion color persists once typed command diverges from prediction

### ISSUE THREAD

**Issue by aw1621107** [tarruda/zsh-autosuggestions#69]
It seems that whatever color zsh-autosuggestions uses for its guess sticks around for the remaining length of the guess once the input diverges from the guess. For example, if `cd` has `~/code/repo` as the guess, but I type `cd ~/code/ocaml/`, parts of `ocaml` will still be the color that zsh-autosuggestions uses, and text after that will be normally colored.

![ex1](https://cloud.githubusercontent.com/assets/566572/8892519/4493ea7c-3329-11e5-9398-db176f8957ec.png)

Deleting a single differently-colored character seems to cause all of the colored text to correct itself.

**Comment by hoodsy** [comment]
Same problem here.

**Comment by ericfreese** [comment]
There's a rewrite underway in PR #91. It's available on branch `v0.1.x`. Please try using that branch, and let me know if it solves your problem.
