### ISSUE TITLE
Join Wahoo?

### ISSUE THREAD

**Issue by bucaran** [tarruda/zsh-autosuggestions#70]
We are still relatively new in town, and just getting started, but we are more stable than the other options, namely OMF. I think some of these functions could be turned into a handful of Wahoo plugins or maybe some could be even make it to core. We are always accepting feature request and feedback. I would love if you could give [Wahoo](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) a look.

Regards :smile:

**Comment by faceleg** [comment]
As much as I love the fish, this is a plugin for ZSH.

**Comment by bucaran** [comment]
Now, I see. Sorry! My bad.

**Comment by faceleg** [comment]
np :dancers:
