### ISSUE TITLE
Plugin breaks zsh vi mode insert

### ISSUE THREAD

**Issue by prurph** [tarruda/zsh-autosuggestions#71]
If vi mode is on (`bindkey -v`), the following happens:

1. Type some text
2. Hit escape to enter normal mode
3. Navigate backwards on the line so your cursor is within that text
4. Pressing `a` (append) or `i` (insert) will cause any text after the cursor to disappear because autosuggestions kicks in with that text after the cursor as the suggestion, and once you diverge from it by inserting text, it's gone.

Contrast this with using the arrow keys to move backwards without ever leaving insert mode and any typed text is inserted in the middle as expected.

**Comment by reinhrst** [comment]
just for info: I'm using vi mode, and cannot reproduce your issue.

**Comment by prurph** [comment]
I'm sorry--I investigated further and the issue is I was doing something like this: http://superuser.com/questions/151803/how-do-i-customize-zshs-vim-mode/#answer-156204 and I think the call to `zle reset-prompt` inside `zle-line-init` was causing the issue.

Sorry for the confusion and many thanks for investigating!
