### ISSUE TITLE
Autosuggestion breaks syntax-highlighting of history searches

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tarruda/zsh-autosuggestions#77]
So, I'm using `zsh-syntax-highlighting`, `zsh-history-substring-search`, and `zsh-autosuggestions` together; unfortunately, once an autosuggestion has highlighted some content, the *length* of that content remains `$AUTOSUGGESTION_HIGHLIGHT_COLOR` indefinitely thereafter:

![](http://i.ell.io/17Kap+)

**Comment by stephenwilley** [comment]
I have exactly the same problem, but strangely only on a Mac (which I see from your gif you're on too).  This doesn't seem to happen on my RHEL6 box.

**Comment by ELLIOTTCABLE** [comment]
@stephenwilley same Zsh version, version of the module, same configuration file, etc? O_O

**Comment by stephenwilley** [comment]
zsh 5.0.8
el Capitan
all the modules are latest from git
.zshrc lists syntax highlighting followed by history substring followed by autosuggestions

**Comment by ericfreese** [comment]
There's a rewrite underway in PR #91. It's available on branch `v0.1.x`. Please try using that branch, and let me know if it solves your problem.
