### ISSUE TITLE
Autosuggestion breaks highlighting on backspace

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tarruda/zsh-autosuggestions#78]
Similar to #77; after a completion occurs, if I delete a few characters, there's stray content and highlighting left *after* the cursor:

![](http://i.ell.io/Vml6+)

**Comment by adambiggs** [comment]
+1

**Comment by faceleg** [comment]
This module needs someone with mad zsh skills to jump in and fix everything

**Comment by ELLIOTTCABLE** [comment]
… scary to see that message from somebody with the ‘collaborator’ tag. :P

**Comment by faceleg** [comment]
Haha, I'm here in an attempt to convince someone to start doing actual work.

**Comment by ericfreese** [comment]
There's a rewrite underway in PR #91. It's available on branch `v0.1.x`. Please try using that branch, and let me know if it solves your problem.

**Comment by dg98** [comment]
I'm still experiencing a similar issue. When I accept an autosuggestion and then delete characters, they're still visually there. I had this issue on both Debian and Gentoo on my machine, but a friend on another Gentoo installation with the same zsh configuration can't reproduce it. I tried in URxvt, Gnome terminal and a tty.
