### ISSUE TITLE
Multiline commands are not handled

### ISSUE THREAD

**Issue by sorin-ionescu** [tarruda/zsh-autosuggestions#81]
It does not handle the `end-of-buffer-or-history` widget. The user has to select each line with autosuggestions.

**Comment by ericfreese** [comment]
@sorin-ionescu There's a rewrite underway in PR #91. It's available on branch `v0.1.x`. Can you verify that the problem still exists on that branch?

**Comment by ericfreese** [comment]
I believe this is no longer an issue on v0.1.x.
