### ISSUE TITLE
I forked this project over to ericfreese/zsh-autosuggest

### ISSUE THREAD

**Issue by ericfreese** [tarruda/zsh-autosuggestions#86]
In trying to fix a few problems with this project, I ended up more or less rewriting a simplified version of it over at [ericfreese/zsh-autosuggest](ericfreese/zsh-autosuggest).

It's pretty primitive, but it works, and it feels pretty solid to me. I'll keep iterating on it, but thought some people might be interested in checking it out since it doesn't look like this project gets a lot of maintenance.

A big change is using POSTDISPLAY instead of LBUFFER and RBUFFER. Seems to make it much more stable and easy to deal with.

It currently doesn't work with the [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) script, but it will soon.

Cheers,
Eric

**Comment by faceleg** [comment]
I would be open to you submitting a PR that basically replaced this one with yours. That way the community doesn't suffer from having to choose between two similar-looking modules when searching for  "the canonical zsh autosuggest" plugin.

**Comment by faceleg** [comment]
I'm sure we can get @tarruda to add you as a collaborator here as well.

**Comment by ericfreese** [comment]
Awesome. I'll try to send a pull request this evening and we can keep the PR open until it's got all the functionality it needs.

Off the top of my head, I'm thinking it needs to:
- work with syntax highlighter
- support all/most of the same key/widget bindings

Cheers!

**Comment by faceleg** [comment]
I'm ecstatic! Thank you!  Many others will feel the same way, I'm sure.

**Comment by ericfreese** [comment]
See PR #91
