### ISSUE TITLE
Cannot tab through multiple choices

### ISSUE THREAD

**Issue by wernight** [tarruda/zsh-autosuggestions#90]
## Setup

Installed as described as OMZ plugin (so it looks like `plugins=(...  zsh-syntax-highlighting zsh-autosuggestions)`). `COMPLETION_WAITING_DOTS` is unset.

    $ bindkey "^I"
    "^I" expand-or-complete

## Bug

Doing `ls <tab>` shows a list of possible arguments (and the gray autosuggestion). Pressing <tab> again chooses the first one, pressing it again should select the second possible choice but instead completes starting from generated string:

    $ ls <tab>

    $ ls <tab>
    foo bar

    $ ls foo/<tab>
    foo bar

    $ ls foo/123<tab>
    foo bar

    $ ls foo/123/456<tab>
    foo bar

If I disable the OMZ plugins `virtualenvwrapper` and `mvn` (2 out of 12 plugins), then <tab> simply erases what comes after the cursor.

**Comment by ericfreese** [comment]
There's a rewrite underway in PR #91. It's available on branch `v0.1.x`. Please try using that branch, and let me know if it solves your problem.

**Comment by wernight** [comment]
Fixed on that branch.

**Comment by ericfreese** [comment]
@wernight Are you still having this problem? Are you sure you're sourcing the script correctly. Can you post your .zshrc?

**Comment by ericfreese** [comment]
Closing this. Please open a new issue with more specific details if you're still having trouble.

**Comment by wernight** [comment]
Still having the error, here the minimal `~/.zshrc` to reproduce with my config following PR #91 (I tried some other variations as well):

````
ZSH=$HOME/.oh-my-zsh
plugins=(zsh-syntax-highlighting zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
autosuggest_start
````

Gives `command not found: autosuggest_start`. I did a git pull on `v0.1.x` just before.

**Comment by wernight** [comment]
By sourcing both files it works but the issue isn't completely gone.

What works:

    $ ls xx<tab>
    $ ls xx1

What doesn't work:

    $ ls <tab>
    $ ls subfolder<CursorHere>~/Desktop

Also bugged same way:

    $ ls <Up/Down>
    $ ls temp1/a1/b1<CursorHere>~/Desktop

**Comment by ericfreese** [comment]
>`plugins=(zsh-syntax-highlighting zsh-autosuggestions)`

This isn't an oh-my-zsh plugin. Please read the installation instructions in the readme.

**Comment by wernight** [comment]
I did. [The plugin exists](https://github.com/tarruda/zsh-autosuggestions/blob/master/zsh-autosuggestions.plugin.zsh) (in a commit "Add symlink for OMZ compatibility") and it's in the [install instructions of zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md)

**Comment by ericfreese** [comment]
@wernight Take a look at #104. PR's welcome!

**Comment by ericfreese** [comment]
@wernight Oh My Zsh support is now in on the [v0.2.x branch](https://github.com/tarruda/zsh-autosuggestions/tree/v0.2.x). Take a look at the README and let me know if you have any problems.
