### ISSUE TITLE
Problems with v0.1.x & tmux

### ISSUE THREAD

**Issue by hcgraf** [tarruda/zsh-autosuggestions#97]
I tried to track down the problems of my comment to PR #91.

The two issues

1. No autocompletions at all
2. Cursor disappearing randomly

seem to be related to tmux in some way.

On Ubuntu Linux 15.10, with zsh 5.1.1, with a completely new user and the minimal zshrc (and no .tmux.conf):
```
autoload -U colors && colors
autoload -Uz compinit && compinit

ZGEN_DIR="${HOME}/.zsh-plugins"
ZGEN_RESET_ON_CHANGE=("${HOME}/.zshrc")

source "${HOME}/.zgen/zgen.zsh"

if ! zgen saved; then
        echo "Creating a zgen save"

        # provides zle hooks
        zgen load willghatch/zsh-hooks

        zgen load tarruda/zsh-autosuggestions.git . v0.1.x

        # save
        zgen save
fi

function my-line-init() {
        # automatically enable autosuggestion
        autosuggest_start
}
hooks-add-hook zle_line_init_hook my-line-init
```
Everything seems to be ok, if

- zsh is started from bash
- tmux is started from bash, and zsh is started within tmux

But I don't get any autosuggestions if 
- tmux is started from zsh (which is usually the case if zsh is the login shell)

**Comment by ericfreese** [comment]
Can you try with a *more* minimal .zshrc? Something like:

```
source ~/path/to/zsh-autosuggestions/autosuggestions.zsh
autosuggest_start
```

**Comment by hcgraf** [comment]
Hm, it seems to work now, also with my less minimal zshrc.
Thanks for your efforts!

**Comment by hcgraf** [comment]
With my full zshrc, the problem persists.
I will see if I find some time to track it down…

**Comment by hcgraf** [comment]
Ok, it was related to my color-scheme, the autosuggestion **was** working, just with the same color as my background >_<
Sorry for the noise…
